{{- if .Values.replica.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: libsql-replica
  labels:
    {{- include "libsql.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  serviceName: libsql-replica
  replicas: {{ .Values.replica.replicaCount }}
  selector:
    matchLabels:
      {{- include "libsql.selectorLabels.replica" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "libsql.selectorLabels.replica" . | nindent 8 }}
    spec:
      containers:
        - name: libsql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
          env:
            - name: SQLD_NODE
              value: replica
            - name: SQLD_PRIMARY_URL
              value: "http://libsql:{{ .Values.service.grpcPort }}"
          resources:
            {{- toYaml .Values.replica.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/sqld
  {{- if .Values.replica.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.replica.persistence.storageClass }}
        storageClassName: {{ .Values.replica.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.replica.persistence.size }}
  {{- end }}
{{- end }}
