apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: libsql-primary
  labels:
    {{- include "libsql.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  serviceName: libsql-primary
  replicas: 1
  selector:
    matchLabels:
      {{- include "libsql.selectorLabels.primary" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "libsql.selectorLabels.primary" . | nindent 8 }}
    spec:
      containers:
        - name: libsql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
          env:
            - name: SQLD_NODE
              value: primary
            {{- if .Values.primary.enableNamespaces }}
            - name: SQLD_ENABLE_NAMESPACES
              value: "true"
            {{- end }}
            - name: SQLD_ADMIN_LISTEN_ADDR
              value: "0.0.0.0:{{ .Values.service.adminPort }}"
          resources:
            {{- toYaml .Values.primary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/sqld
  {{- if .Values.primary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.primary.persistence.storageClass }}
        storageClassName: {{ .Values.primary.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.primary.persistence.size }}
  {{- end }}
