apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "buntime.fullname" . }}-plugins
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.plugins.accessMode }}
  {{- if .Values.persistence.plugins.storageClass }}
  storageClassName: {{ .Values.persistence.plugins.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.plugins.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "buntime.fullname" . }}-apps
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.apps.accessMode }}
  {{- if .Values.persistence.apps.storageClass }}
  storageClassName: {{ .Values.persistence.apps.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.apps.size }}
