{{- if .Values.buntime.libsqlAuthToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buntime.fullname" . }}
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
type: Opaque
stringData:
  LIBSQL_AUTH_TOKEN: {{ .Values.buntime.libsqlAuthToken | quote }}
{{- end }}
