{{- if or .Values.buntime.rootKey .Values.buntime.libsqlAuthToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buntime.fullname" . }}
  labels:
    {{- include "buntime.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.buntime.rootKey }}
  ROOT_KEY: {{ .Values.buntime.rootKey | quote }}
  {{- end }}
  {{- if .Values.buntime.libsqlAuthToken }}
  LIBSQL_AUTH_TOKEN: {{ .Values.buntime.libsqlAuthToken | quote }}
  {{- end }}
{{- end }}
